// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: events/v1/order.proto

package events_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported payment methods
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED    PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CARD           PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_SBP            PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD    PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_INVESTOR_MONEY PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CARD",
		2: "PAYMENT_METHOD_SBP",
		3: "PAYMENT_METHOD_CREDIT_CARD",
		4: "PAYMENT_METHOD_INVESTOR_MONEY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":    0,
		"PAYMENT_METHOD_CARD":           1,
		"PAYMENT_METHOD_SBP":            2,
		"PAYMENT_METHOD_CREDIT_CARD":    3,
		"PAYMENT_METHOD_INVESTOR_MONEY": 4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_order_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_events_v1_order_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_order_proto_rawDescGZIP(), []int{0}
}

// Event for kafka comsumer in paid method
type OrderPaid struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventUuid       string                 `protobuf:"bytes,1,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	OrderUuid       string                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid        string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PaymentMethod   PaymentMethod          `protobuf:"varint,4,opt,name=payment_method,json=paymentMethod,proto3,enum=events.v1.PaymentMethod" json:"payment_method,omitempty"`
	TransactionUuid string                 `protobuf:"bytes,5,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderPaid) Reset() {
	*x = OrderPaid{}
	mi := &file_events_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaid) ProtoMessage() {}

func (x *OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaid.ProtoReflect.Descriptor instead.
func (*OrderPaid) Descriptor() ([]byte, []int) {
	return file_events_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPaid) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *OrderPaid) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *OrderPaid) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *OrderPaid) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *OrderPaid) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

var File_events_v1_order_proto protoreflect.FileDescriptor

const file_events_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/order.proto\x12\tevents.v1\"\xd2\x01\n" +
	"\tOrderPaid\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tR\teventUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12?\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2\x18.events.v1.PaymentMethodR\rpaymentMethod\x12)\n" +
	"\x10transaction_uuid\x18\x05 \x01(\tR\x0ftransactionUuid*\xa3\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x01\x12\x16\n" +
	"\x12PAYMENT_METHOD_SBP\x10\x02\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x03\x12!\n" +
	"\x1dPAYMENT_METHOD_INVESTOR_MONEY\x10\x04B>Z<back/GoSpaceShipService/shared/pkg/proto/events/v1;events_v1b\x06proto3"

var (
	file_events_v1_order_proto_rawDescOnce sync.Once
	file_events_v1_order_proto_rawDescData []byte
)

func file_events_v1_order_proto_rawDescGZIP() []byte {
	file_events_v1_order_proto_rawDescOnce.Do(func() {
		file_events_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)))
	})
	return file_events_v1_order_proto_rawDescData
}

var file_events_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_order_proto_goTypes = []any{
	(PaymentMethod)(0), // 0: events.v1.PaymentMethod
	(*OrderPaid)(nil),  // 1: events.v1.OrderPaid
}
var file_events_v1_order_proto_depIdxs = []int32{
	0, // 0: events.v1.OrderPaid.payment_method:type_name -> events.v1.PaymentMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_v1_order_proto_init() }
func file_events_v1_order_proto_init() {
	if File_events_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_order_proto_goTypes,
		DependencyIndexes: file_events_v1_order_proto_depIdxs,
		EnumInfos:         file_events_v1_order_proto_enumTypes,
		MessageInfos:      file_events_v1_order_proto_msgTypes,
	}.Build()
	File_events_v1_order_proto = out.File
	file_events_v1_order_proto_goTypes = nil
	file_events_v1_order_proto_depIdxs = nil
}
