// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateOrder implements CreateOrder operation.
//
// Create order for a user with some parts.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUUID implements GetOrderByUUID operation.
//
// Get order by uuid.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUUID(ctx context.Context, params GetOrderByUUIDParams) (r GetOrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderCancel implements OrderCancel operation.
//
// Cancel order by order_uuid.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) OrderCancel(ctx context.Context, params OrderCancelParams) (r OrderCancelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderPay implements OrderPay operation.
//
// Pay the order, change OrderStatus and PaymentMethod.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (r OrderPayRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
