// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateOrder implements CreateOrder operation.
	//
	// Create order for a user with some parts.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderByUUID implements GetOrderByUUID operation.
	//
	// Get order by uuid.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUUID(ctx context.Context, params GetOrderByUUIDParams) (GetOrderByUUIDRes, error)
	// OrderCancel implements OrderCancel operation.
	//
	// Cancel order by order_uuid.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	OrderCancel(ctx context.Context, params OrderCancelParams) (OrderCancelRes, error)
	// OrderPay implements OrderPay operation.
	//
	// Pay the order, change OrderStatus and PaymentMethod.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (OrderPayRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
