// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderService
func (_mock *OrderService) CancelOrder(ctx context.Context, order_uuid string) error {
	ret := _mock.Called(ctx, order_uuid)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, order_uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order_uuid string
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, order_uuid interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, order_uuid)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, order_uuid string)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(err error) *OrderService_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, order_uuid string) error) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type OrderService
func (_mock *OrderService) CreateOrder(ctx context.Context, user_uuid string, part_uuids []string) (*model.Order, error) {
	ret := _mock.Called(ctx, user_uuid, part_uuids)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*model.Order, error)); ok {
		return returnFunc(ctx, user_uuid, part_uuids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *model.Order); ok {
		r0 = returnFunc(ctx, user_uuid, part_uuids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, user_uuid, part_uuids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - user_uuid string
//   - part_uuids []string
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, user_uuid interface{}, part_uuids interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, user_uuid, part_uuids)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, user_uuid string, part_uuids []string)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(order *model.Order, err error) *OrderService_CreateOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, user_uuid string, part_uuids []string) (*model.Order, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUUID provides a mock function for the type OrderService
func (_mock *OrderService) GetOrderByUUID(ctx context.Context, order_uuid string) (*model.Order, error) {
	ret := _mock.Called(ctx, order_uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return returnFunc(ctx, order_uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = returnFunc(ctx, order_uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, order_uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUUID'
type OrderService_GetOrderByUUID_Call struct {
	*mock.Call
}

// GetOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - order_uuid string
func (_e *OrderService_Expecter) GetOrderByUUID(ctx interface{}, order_uuid interface{}) *OrderService_GetOrderByUUID_Call {
	return &OrderService_GetOrderByUUID_Call{Call: _e.mock.On("GetOrderByUUID", ctx, order_uuid)}
}

func (_c *OrderService_GetOrderByUUID_Call) Run(run func(ctx context.Context, order_uuid string)) *OrderService_GetOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetOrderByUUID_Call) Return(order *model.Order, err error) *OrderService_GetOrderByUUID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_GetOrderByUUID_Call) RunAndReturn(run func(ctx context.Context, order_uuid string) (*model.Order, error)) *OrderService_GetOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type OrderService
func (_mock *OrderService) PayOrder(ctx context.Context, PaymentMethod model.PaymentMethod, order_uuid string) (string, error) {
	ret := _mock.Called(ctx, PaymentMethod, order_uuid)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PaymentMethod, string) (string, error)); ok {
		return returnFunc(ctx, PaymentMethod, order_uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PaymentMethod, string) string); ok {
		r0 = returnFunc(ctx, PaymentMethod, order_uuid)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PaymentMethod, string) error); ok {
		r1 = returnFunc(ctx, PaymentMethod, order_uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - PaymentMethod model.PaymentMethod
//   - order_uuid string
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, PaymentMethod interface{}, order_uuid interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, PaymentMethod, order_uuid)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, PaymentMethod model.PaymentMethod, order_uuid string)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PaymentMethod
		if args[1] != nil {
			arg1 = args[1].(model.PaymentMethod)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(s string, err error) *OrderService_PayOrder_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, PaymentMethod model.PaymentMethod, order_uuid string) (string, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
