// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewOrderProducerService creates a new instance of OrderProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProducerService {
	mock := &OrderProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderProducerService is an autogenerated mock type for the OrderProducerService type
type OrderProducerService struct {
	mock.Mock
}

type OrderProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderProducerService) EXPECT() *OrderProducerService_Expecter {
	return &OrderProducerService_Expecter{mock: &_m.Mock}
}

// ProduceOrderPaid provides a mock function for the type OrderProducerService
func (_mock *OrderProducerService) ProduceOrderPaid(ctx context.Context, event model.OrderPaidEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderProducerService_ProduceOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderPaid'
type OrderProducerService_ProduceOrderPaid_Call struct {
	*mock.Call
}

// ProduceOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidEvent
func (_e *OrderProducerService_Expecter) ProduceOrderPaid(ctx interface{}, event interface{}) *OrderProducerService_ProduceOrderPaid_Call {
	return &OrderProducerService_ProduceOrderPaid_Call{Call: _e.mock.On("ProduceOrderPaid", ctx, event)}
}

func (_c *OrderProducerService_ProduceOrderPaid_Call) Run(run func(ctx context.Context, event model.OrderPaidEvent)) *OrderProducerService_ProduceOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderPaidEvent
		if args[1] != nil {
			arg1 = args[1].(model.OrderPaidEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderProducerService_ProduceOrderPaid_Call) Return(err error) *OrderProducerService_ProduceOrderPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderProducerService_ProduceOrderPaid_Call) RunAndReturn(run func(ctx context.Context, event model.OrderPaidEvent) error) *OrderProducerService_ProduceOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}
